name: Grid snake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "* */12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3.1.0
        with:
          github_user_name: dothanhtu1804
          outputs: |
            dist/grid-snake.svg
            dist/grid-snake-dark.svg?palette=github-dark
        env:
          # a GitHub token is required to fetch the contribution calendar from GitHub API
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit temporary files
        run: |
          git add .
          git commit -m "Temporary commit for SVG files" || true

      - name: Pull
        run: git pull origin main

      - uses: stefanzweifel/git-auto-commit-action@v4.15.1
        with:
          commit_message: "grid snake"
          file_pattern: 'dist/*.svg'
          commit_user_name: dothanhtu1804
          commit_user_email: dothanhtu.1804@gmail.com
          commit_author: Đỗ Thanh Tú <dothanhtu.1804@gmail.com>